import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { useState, useEffect } from 'react';

import * as queries from '../src/graphql/queries';

import { Amplify, API, withSSRContext } from "aws-amplify";
// import { listPosts } from "../src/graphql/queries";

export async function getServerSideProps({ req }) {
  // Notice how the server uses `API` from `withSSRContext`, instead of the top-level `API`.
  const SSR = withSSRContext({ req })
  const { data } = await SSR.API.graphql({
    query: `
  query ListTodos(
    $filter: ModelTodoFilterInput
    $limit: Int
    $nextToken: String
  ) {
    listTodos(filter: $filter, limit: $limit, nextToken: $nextToken) {
      items {
        id
        name
        description
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`});

  console.log("ssr", data)

  return {
    props: {
      posts: data.listTodos.items
    }
  }
}

export default function Home({ posts }) {


  // const [posts, setPosts] = useState(undefined);

  // useEffect(() => {
  //   console.log(posts)
  // }, [])


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Powered by AWS Amplify
        </p>

        <div className={styles.grid}>
          {posts && posts.map(item =>
            <a key={item.id} href="https://nextjs.org/docs" className={styles.card}>
              <h2>{item.name} &rarr;</h2>
              <p>{item.description}</p>
            </a>
          )}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
